=== Daniolo0589/KingdomCake/postres.dtd
<!ELEMENT postres (postre+)>
<!ELEMENT postre (nombre,sabor,precio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT sabor (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST postre
          id CDATA #REQUIRED
>

=== Daniolo0589/KingdomCake/postres.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="https://daniolo0589.github.io/KingdomCake/estiloxml.css"?>
<!DOCTYPE postres SYSTEM "postres.dtd">
<postres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="postres.xsd">

	<postre id="1">
		<nombre> coulant de chocolate </nombre>
		<sabor> chocolate </sabor>
		<precio> 5.99€ </precio>
	</postre>
		
	<postre id="2">
		<nombre> yougurt de fresa </nombre>
		<sabor> fresa </sabor>
		<precio> 6.99€ </precio>
	</postre>
		
	<postre id="3">
		<nombre> flan de vainilla </nombre>
		<sabor> vainilla </sabor>
		<precio> 10.99€ </precio>
	</postre>

	<postre id="4">
		<nombre> Pie de Fresa </nombre>
		<sabor> fresa </sabor>
		<precio> 19.99€ </precio>
	</postre>

	<postre id="5">
		<nombre> Helado de Fresa </nombre>
		<sabor> fresa </sabor>
		<precio> 7.99€ </precio>
	</postre>

	<postre id="6">
		<nombre> Pastel de chocolate </nombre>
		<sabor> chocolate </sabor>
		<precio> 11.99€ </precio>
	</postre>

	<postre id="7">
		<nombre> Helado de Chocolate </nombre>
		<sabor> chocolate </sabor>
		<precio> 7.99€ </precio>
	</postre>

	<postre id="8">
		<nombre> Pastel de chocolate </nombre>
		<sabor> chocolate </sabor>
		<precio> 11.99€ </precio>
	</postre>

</postres>
